### ISSUE TITLE
Which architectures are supported ?

### ISSUE THREAD

**Issue by dummys** [vrtadmin/FIRST#4]
Hi,

I searched in your documentation and didn't found this information...
Is ARM and MIPS supported ?
Thanks.

**Comment by demonduck** [comment]
Hey,

FIRST is a framework that will support any architecture if an Engine exists that can work with the architecture. Currently the Mnemonic Hashing and Basic Masking Engines work only for Intel (this is due to using distorm3 for prototyping). We would like to move from distorm3 to capstone to provide an easier method for supporting more architectures. The Exact Match Engine will work on any architecture, but clearly isn't as useful for finding non exact matches. 

If you'd like to work on creating an Engine then please let me know :)

**Comment by dummys** [comment]
Oh yeah ok. And what about using BinDiff as engine and [Diaphora](https://github.com/joxeankoret/diaphora) as engine ?

**Comment by demonduck** [comment]
BinDiff and Diaphora do great at diffing two samples. The algorithms they use are resource intensive, which is not that noticeable (or is acceptable) when comparing a small set of functions. With FIRST, we wanted to provide a quick way to preserve analysis. FIRST can include an Engine that replicates BinDiff, Diaphora, etc. but it will have a performance hit. 

Let's say there are a million functions in FIRST's dbs, and you search FIRST for one function in your local IDB. The amount of processing required to do that diff and the delay would not be practical/helpful for many end users since each function would need to be compared against the incoming query. Now imagine, you have a sample with a thousand functions... This doesn't mean you can't stand up your own FIRST server to conduct more time intensive matches, however, the public server will have to make performance decisions to allow timely retrieval of small and larger queries.

Additionally, since FIRST's goal is to preserve analysis and function annotations the end user will not be provided with a side by side comparison like Bindiff/Diaphora/etc., only the metadata (function name, prototype, comment).
